plugins {
    id 'com.android.application' version '8.1.0'
}

android {
    namespace 'com.vr.shizuku.manager'
    compileSdk 34

    defaultConfig {
        applicationId "com.vr.shizuku.manager"
        minSdk 30
        targetSdk 34
        versionCode 1
        versionName "1.0"
    }

    signingConfigs {
        release {
            storeFile file('keystore.jks')
            storePassword 'password123'
            keyAlias 'keyalias'
            keyPassword 'password123'
        }
    }

    buildTypes {
        release {
            signingConfig signingConfigs.release
        }
    }
}

dependencies {
    implementation 'androidx.appcompat:appcompat:1.6.1'
}
